[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.10", features = ["derive"] }
dotenv = "0.15.0"
itertools = "0.12.0"
reqwest = { version = "0.11.22", features = ["blocking", "cookies"] }
